-- CURRENT_TIER (1,2,3,4) for each COUNTY
-- 58 rows

select
  COUNTY,
  CURRENT_TIER
from
  COVID.PRODUCTION.VW_CDPH_COUNTY_TIER_DATA
where
  date = (select max(DATE) from COVID.PRODUCTION.VW_CDPH_COUNTY_TIER_DATA)