-- Data for Postvax Covid Charts

SELECT DATE,
    UNVAX_CASE_RATE,
    UNVAX_HOSP_RATE,
    UNVAX_DEATH_DOD_RATE,
    VAX_CASE_RATE,
    VAX_HOSP_RATE,
    VAX_DEATH_DOD_RATE,
    REPORT_DATE
FROM COVID.DEVELOPMENT.CDPH_POSTVAX_CASE_HOSP_DEATH_ANYVAX 
WHERE (REPORT_DATE=(select max(REPORT_DATE) from COVID.DEVELOPMENT.CDPH_POSTVAX_CASE_HOSP_DEATH_ANYVAX)) 
      AND (VAX_CASE_RATE IS NOT NULL)
      AND AREA='California'
ORDER BY DATE
;