-- Race/ethnicity of total cases, deaths, testing by county
-- 1,593 rows
-- by METRIC (deaths,cases,tests)
--   by COUNTY 
--   by DEMOGRAPHIC_SET_CATEGORY (White, Latino, American Indian, etc.)

select
  COUNTY,
  DEMOGRAPHIC_SET,
  DEMOGRAPHIC_SET_CATEGORY,
  METRIC,
  METRIC_VALUE,
  METRIC_VALUE_PER_100K,
  APPLIED_SUPPRESSION,
  POPULATION_PERCENTAGE,
  METRIC_TOTAL_PERCENTAGE,
  METRIC_VALUE_30_DAYS_AGO,
  METRIC_VALUE_PER_100K_30_DAYS_AGO, 
  METRIC_VALUE_PER_100K_DELTA_FROM_30_DAYS_AGO, 
  METRIC_TOTAL_PERCENTAGE_30_DAYS_AGO, 
  METRIC_VALUE_PERCENTAGE_DELTA_FROM_30_DAYS_AGO 
from
  PRODUCTION.VW_CDPH_DEMOGRAPHIC_RATE_CUMULATIVE
where
  DEMOGRAPHIC_SET = 'race_ethnicity'
  and
  COUNTY IS NOT NULL
