select
  COUNTY,
  METRIC,
  MISSING,
  NOT_MISSING,
  TOTAL,
  PERCENT_COMPLETE,
  PERCENT_COMPLETE_30_DAYS_PRIOR,
  PERCENT_COMPLETE_30_DAYS_DIFF,
  REPORT_DATE
from
  PRODUCTION.VW_CDPH_DEMOGRAPHIC_COMPLETENESS
where
  REPORT_DATE = (select max(REPORT_DATE) from PRODUCTION.VW_CDPH_DEMOGRAPHIC_COMPLETENESS)