select
  AGE_GROUP,
  GENDER,
  RACE_ETHNICITY,
  POPULATION,
  SF_LOAD_TIMESTAMP
from
  COVID.PRODUCTION.CDPH_STATIC_DEMOGRAPHICS
where
  SF_LOAD_TIMESTAMP = (select max(SF_LOAD_TIMESTAMP) from PRODUCTION.CDPH_STATIC_DEMOGRAPHICS)