select
    DATE,
    AREA "REGION",

    CASES,
    REPORTED_CASES,
    PROBABLE_CASES,
    COMBINED_CASES,
    AVG_CASE_RATE_PER_100K_7_DAYS,
    AVG_CASE_REPORT_RATE_PER_100K_7_DAYS,
    AVG_PROBABLE_CASE_RATE_PER_100K_7_DAYS,
    AVG_COMBINED_CASE_RATE_PER_100K_7_DAYS,

    DEATHS,
    REPORTED_DEATHS,
    PROBABLE_DEATHS,
    COMBINED_DEATHS,
    AVG_DEATH_RATE_PER_100K_7_DAYS,
    AVG_DEATH_REPORT_RATE_PER_100K_7_DAYS,
    AVG_PROBABLE_DEATH_RATE_PER_100K_7_DAYS,
    AVG_COMBINED_DEATH_RATE_PER_100K_7_DAYS,

    TOTAL_TESTS,
    REPORTED_TESTS,
    AVG_TEST_RATE_PER_100K_7_DAYS,
    AVG_TEST_REPORT_RATE_PER_100K_7_DAYS,
    TEST_POSITIVITY_RATE_7_DAYS,
    DAILY_TEST_POSITIVITY_RATE
from 
    COVID.DEVELOPMENT.VW_CDPH_COUNTY_AND_STATE_TIMESERIES_METRICS
where
    AREA not in ('Out of state','Unknown') 
    and DATE >= '2020-03-01'
order by
    AREA,
    DATE DESC
