WITH main_q AS
    (SELECT * FROM COVID.PRODUCTION.CDPH_RACE_ETHNICITY_TIMESERIES_STAGE)
SELECT
    LOCATION_LEVEL,
    LOCATION,
    DATE,
    DEMOG,
    DEMOG_CAT,
    METRIC_CAT,
    METRIC,
    VALUE,
    REPORT_DATE
FROM main_q
WHERE LOCATION='CA' AND REPORT_DATE = (SELECT MAX(REPORT_DATE) FROM main_q)
ORDER BY METRIC_CAT, METRIC, DEMOG_CAT, DATE
;
