select
    DATE,
    AREA "REGION",
    
    CASES,
    REPORTED_CASES,
    AVG_CASE_RATE_PER_100K_7_DAYS,
    AVG_CASE_REPORT_RATE_PER_100K_7_DAYS,
    EPISODE_UNCERTAINTY_PERIOD,
    
    DEATHS,
    REPORTED_DEATHS,
    DEATH_UNCERTAINTY_PERIOD,
    AVG_DEATH_RATE_PER_100K_7_DAYS,
    AVG_DEATH_REPORT_RATE_PER_100K_7_DAYS,
    
    TOTAL_TESTS,
    REPORTED_TESTS,
    AVG_TEST_RATE_PER_100K_7_DAYS,
    AVG_TEST_REPORT_RATE_PER_100K_7_DAYS,
    TEST_POSITIVITY_RATE_7_DAYS,
    TESTING_UNCERTAINTY_PERIOD
from 
    COVID.PRODUCTION.VW_CDPH_COUNTY_AND_STATE_TIMESERIES_METRICS
where
    AREA not in ('Out of state','Unknown') 
    and DATE >= '2020-03-01'
order by
    AREA,
    DATE DESC