-- Data for Postvax Covid Charts

SELECT DATE,AREA,AREA_TYPE,
UNVAX_CASES_EPDATE,UNVAX_HOSP_EPDATE,UNVAX_DEATH_DOD,
BREAKTHROUGH_CASES_EPDATE,BREAKTHROUGH_HOSP_EPDATE,BREAKTHROUGH_DEATH_DOD,
VAX_DENOM,UNVAX_DENOM,
UNVAX_CASE_RATE,UNVAX_HOSP_RATE,UNVAX_DEATH_RATE,
BREAKTHROUGH_CASE_RATE,BREAKTHROUGH_HOSP_RATE,BREAKTHROUGH_DEATH_RATE
FROM COVID.PRODUCTION.CDPH_POSTVAX_CASE_HOSP_DEATH 
WHERE (REPORT_DATE=(select max(REPORT_DATE) from COVID.PRODUCTION.CDPH_POSTVAX_CASE_HOSP_DEATH)) 
      AND (BREAKTHROUGH_CASE_RATE IS NOT NULL)
ORDER BY DATE
;
